services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
# docker compose -p nestjs-mysql up -d
