services:
  #   mongodb:
  #     image: mongo:5.0.15
  #     environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITDB_ROOT_PASSWORD: 123456
  #     ports:
  #       - 27017:27017
  #     volumes:
  #       - mongodb_data_container:/data/db

  # volumes:
  #   mongodb_data_container:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - db:/var/lib/mysql
volumes:
  db:

  # docker compose -p nestjs-mongodb up -d
